language: python
python:
    - 2.7
before_install:
    - scripts/travis.install.third.party.sw.ngsphy.sh
install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - scripts/ngsphy.test.sh
