language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - tar -zxvf dist/ngsphy-1.0.0.tar.gz
  - sudo python dist/ngsphy-1.0.0/setup.py install
# command to run tests
script: ngsphy
